export const basketLayoutStyle = {
  div: {
    position: 'fixed',
    backgroundColor: '#FFFFFF',
    width: '40%',
    height: '100vh',
    top: 0,
    right: 0,
    zIndex: 100000000,
  },
  div2: {
    overflow: 'hidden',
    width: '1000%',
    margin: '2rem 2rem 10px 2rem',
  },
  h3: {
    fontSize: '1.25rem',
    textAlign: 'center',
    fonWeight: '700',
    textDecoration: 'none',
    textTransform: 'uppercase',
    cursorPointer: 'none',
  },
  p: {
    fontSize: '1.25rem',
    fontStyle: 'Regular',
    textAlign: 'center',
    fonWeight: '400',
    textDecoration: 'none',
    textTransform: 'uppercase',
    cursorPointer: 'none',
    marginTop: '28px',
  },
  button: {
    color: '#FFFFFF',
    backgroundColor: '#000000',
    borderRadius: 'none',
    maxWidth: '426px',
    width: '100vw',
    fontSize: '1.25rem',
    fontStyle: 'Regular',
    textAlign: 'center',
    fonWeight: '700',
    textDecoration: 'none',
    textTransform: 'uppercase',
  },
}
